approval_policy = "never"
approvals_reviewer = "user"
sandbox_mode = "danger-full-access"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"

#model_context_window = 400000
#model_auto_compact_token_limit = 310000
#model_catalog_json = "~/.codex/model_catalog.json"

remote_compaction_v2 = true
responses_websocket_response_processed = true
service_tier = "default"

[features]
hooks = true
multi_agent = true
remote_connections = true
terminal_resize_reflow = true

[projects."/home/gary"]
trust_level = "trusted"

[projects."/home/gary/git/cffex"]
trust_level = "trusted"

[projects."/home/gary/.codex"]
trust_level = "trusted"

[projects."/home/gary/git/simplepower"]
trust_level = "trusted"

[projects."/home/scpuser/Gary/ocg-test-bed"]
trust_level = "trusted"

[projects."/home/gary/git/ocg-test-bed"]
trust_level = "trusted"

[projects."/home/scpuser/.codex"]
trust_level = "trusted"

[projects."/home/gary/git/fpga_sw"]
trust_level = "trusted"

[projects."/home/gary/git/yt-subtitle"]
trust_level = "trusted"

[projects."/home/gary/bin"]
trust_level = "trusted"

[projects."/home/gary/git/linux"]
trust_level = "trusted"

[projects."/home/gary/git/hkex_python"]
trust_level = "trusted"

[projects."/home/scpuser/network_scripts"]
trust_level = "trusted"

[projects."/home/scpuser/Gary/ocg_server"]
trust_level = "trusted"

[projects."/home/gary/cffex/cache"]
trust_level = "trusted"

[projects."/home/gary/cffex/markout"]
trust_level = "trusted"

[projects."/home/gary/git/codex"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "current-dir", "run-state", "context-used", "five-hour-limit", "weekly-limit", "codex-version", "fast-mode"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[tui.keymap.editor]
insert_newline = ["ctrl-j", "ctrl-m", "enter", "shift-enter", "alt-enter"]

[agents]
max_threads = 30

[notice]
fast_default_opt_out = true
